[package]
name = "r1"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
reqwest = "0.12.12"
local-ip-address = "0.6.3"
colored = "3.0"
indicatif = "0.17.9"
